### PR TITLE
fit and predict methods updated to avoid multiple trainings

### PR DESCRIPTION
**Pull request by andrepugni**
Hi Dan,

I have updated the code to avoid retraining in the predict method.
Cheers,

Andrea

### CODE REVIEW

**Review by saattrupdan — CHANGES_REQUESTED** [review]
Looks good! Just got some small stylistic changes.

**Comment by saattrupdan** [comment]
@andrepugni  Why did you close the PR?

**Review by saattrupdan — APPROVED** [review]
Looks good!

**Comment by andrepugni** [comment]
misclick lol

**Pull request merged**
